spring.application.name=bibliotheque-web

#Localisation de la base de donnée

spring.datasource.url=jdbc:mysql://localhost:3306/library


#Savoir qui se connect !

spring.datasource.username=root
spring.datasource.password=
# (Laisse vide après le = si tu n'avais pas de mot de passe sur l'ancien projet)

#Le pilote (pas nécessaire mais au cas où)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver